version: 2.1

orbs:
  newman: postman/newman@dev:alpha

jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout

      - newman/newman-run:
          collection: https://api.getpostman.com/collections/14272639-a12ec866-1d76-43e2-8eee-d4821733f158?apikey=$POSTMAN_API_KEY


workflows:
  run-collection-workflow:
    jobs:
      - newman-collection-run
