version: 2.1
orbs:
  newman: postman/newman@dev:alpha

jobs:
  say-hello:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, world!"

  run-collection:
    docker:
      # replace with your preferred image
      - image: postman/newman:latest

    steps:
      - checkout
      - newman/newman-run:
          collection: https://api.getpostman.com/collections/14272639-a12ec866-1d76-43e2-8eee-d4821733f158?apikey=$POSTMAN_API_KEY



workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - run-collection
